### ISSUE TITLE
Lighty overlay is sky coloured instead of orange/green/red

### ISSUE THREAD

**Issue by Traehgniw** [SchmarrnDevs/Lighty#47]
Using the latest Forge version with Rubidium

**Comment by andi-makes** [comment]
Thank you for opening this issue!

I cannot reproduce this issue on my end with Lighty v2.1.0 and Rubidium 0.7.0a and Forge 47.1.46, can you please provide the specific mod and forge versions you are using?

Are there any other mods you haven't mentioned that could be causing the problem?

Also consider attaching a screenshot showing the problem, something like this one:

![image](https://github.com/SchmarrnDevs/Lighty/assets/26302678/34f3d37a-7c51-46df-8139-07218670d3c2)

Hopefully we can get this fixed soon!

**Comment by Traehgniw** [comment]
I'm on rubidum 0.6.5, not 0.7, because 0.7 was causing crashes with Create and Rubidium Options and made Dynamic Lights not work. Here is a picture from in-game daytime.

![image](https://github.com/SchmarrnDevs/Lighty/assets/42482668/caedebfa-a49f-4431-a27f-565afd7ea1d3)

and another
![image](https://github.com/SchmarrnDevs/Lighty/assets/42482668/a0be4911-8234-4257-a4b7-13c7945f55ad)

The same east/west hallway, from two different angles at sunset (it cares about facing direction at sunrise and sunset)

![image](https://github.com/SchmarrnDevs/Lighty/assets/42482668/71ddcde0-0dac-4cb7-a2cd-0c6b576fc97d)

![image](https://github.com/SchmarrnDevs/Lighty/assets/42482668/7e4c5068-67aa-41c3-b341-239bfe61bf26)

nighttime
![image](https://github.com/SchmarrnDevs/Lighty/assets/42482668/d3e88fa3-e24f-4c50-8191-5f5bb363362b)

**Comment by andi-makes** [comment]
Thank you for providing additional information!

Sadly, I won't fix this, because it is already fixed with more recent Rubidium.
Additionally, because this is a bug in Rubidium and not in Lighty, I cannot reasonably fix it, even if I wanted to.

I can offer the following suggestions/solutions:

- Downgrade Lighty to a version where it works with the old Rubidium version
- Maybe try out [embeddium](https://modrinth.com/mod/embeddium) and [TexTrue's Embeddium Options](https://modrinth.com/mod/textrues-embeddium-options), which claims to be a sodium fork for forge that is more compatible with other forge mods than rubidium.

From my limited testing, embeddium works just fine with the latest create version, while rubidium caused a crash. The Lighty overlays also are correctly colored with embeddium installed.

Again, thank you for opening this issue. I am sorry that I cannot fix this on my end, but hopefully embeddium does the trick for you. Please let me know if it does, so that I can recommend embeddium to other people that may have the same issue! Thanks!

**Comment by Edrow-6** [comment]
Hi, I've had the same problem with Fabric since I updated the mod (I use Sodium 0.5.2)

Without Shaders (same issue):
![image](https://github.com/SchmarrnDevs/Lighty/assets/25459251/e64cd5da-8d54-4bb7-a864-3ac382f4f8f6)

With Shaders (no issue):
![image](https://github.com/SchmarrnDevs/Lighty/assets/25459251/945058b2-d172-4957-8dda-ee6fe2e1c4a7)

**Comment by Traehgniw** [comment]
I've also noticed it in Fabric, but with the really weird caveat that in the same server and same game session it will sometimes work and sometimes not.

Using Lighty 2.1.0, Sodium 0.5.2, and Fabric 0.14.22 with Fabric API 0.88.1

It's very very inconsistent. Some areas of the world have it work and some don't. It seems to work more often in the Nether than in the Overworld? But still not all the time.

**Comment by andi-makes** [comment]
It did work in my dev env, but after someone reporting they had this issue in my discord on fabric without any other mods installed, I tried it in a normal production environment, where it didn't work.

Also, on quilt it seems to work just fine, so I believe that it has something to do with fapi.

But this is really really weird, and I don't even know how to deal with it, because it works on fabric in my dev env. It is very confusing

**Comment by Traehgniw** [comment]
Very weird!

Did you try several different areas of the world to see if it broke in any places?

**Comment by andi-makes** [comment]
Not yet, will try when I have time to work on Lighty again

**Comment by andi-makes** [comment]
![image](https://github.com/SchmarrnDevs/Lighty/assets/26302678/29c02fcb-ab45-4df3-8f83-fe8ad3847e2b)

I was able to reproduce it in the dev env! (it does look kinda fancy tbh)

Oh my god it is a fog issue, I am pretty sure

**Comment by andi-makes** [comment]
I think I have fixed it, will probably release tomorrow

**Comment by andi-makes** [comment]
Published a release (actually, two, because the first one didn't entirely fix it) with a fix! Check out [Modrinth](https://modrinth.com/mod/lighty/versions) or [GitHub Releases](https://github.com/SchmarrnDevs/Lighty/releases/tag/v2.1.2%2B1.20.1)

Thank you all for providing details about the issue, you are the best :heart:
